//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Orders = new HashSet<Orders>();
            this.CustomerDemographics = new HashSet<CustomerDemographics>();
        }
        [System.ComponentModel.DataAnnotations.Display(Name = "公司代號")]
        public string CustomerID { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "公司名稱")]
        public string CompanyName { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "聯絡人姓名")]
        public string ContactName { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "聯絡人職稱")]
        public string ContactTitle { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "公司地址")]
        public string Address { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "所在城市")]
        public string City { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "所在地區")]
        public string Region { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "郵遞區碼")]
        public string PostalCode { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "國家")]
        public string Country { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "聯絡電話")]
        public string Phone { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "傳真號碼")]
        public string Fax { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDemographics> CustomerDemographics { get; set; }
    }
}
